/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xue_song_ffmpeg_FPlayer */

#ifndef _Included_com_xue_song_ffmpeg_FPlayer
#define _Included_com_xue_song_ffmpeg_FPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xue_song_ffmpeg_FPlayer
 * Method:    doOutput
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_xue_song_ffmpeg_FPlayer_doOutput
  (JNIEnv *, jclass, jstring, jstring);
#ifdef __cplusplus
}
#endif
#endif
